### ISSUE TITLE
Improve smoke spec performance

### ISSUE THREAD

**Issue by blocknotes** [solidusio-contrib/solidus_dev_support#32]
We have noticed that the smoke spec is slow on CI.
An improvement here would be good.
After an initial investigation, we could try using only an in-memory SQLite DB

**Comment by blocknotes** [comment]
The slowness seems not related to the DB but to the `bundle install` command executed in the spec.
An idea could be to create a CircleCI procedure to execute a `bundle install` in advance for the dummy extension that will be generated. It could be done using the [template Gemfile](https://github.com/solidusio-contrib/solidus_extension_dev_tools/blob/master/lib/solidus_extension_dev_tools/templates/extension/Gemfile), generating a fake gemspec and using `vendor/bundle` as bundle install path.
But actually this is getting tricky for the benefits that it could bring so I'm going to hold this one for now.

**Comment by elia** [comment]
Fixed by #44
