### ISSUE TITLE
Improve rake tasks

### ISSUE THREAD

**Issue by kennyadsl** [solidusio-contrib/solidus_dev_support#42]
While trying to use solidus_dev_support into [solidus_auth_devise](https://github.com/solidusio/solidus_auth_devise), I noticed some things that could be improved:

- `rake test_app` should be preserved and aliased to the new `extension:test_app` task, to preserve backward compatibility.
- `rake test_app` [could need arguments passed](https://github.com/solidusio/solidus_auth_devise/blob/3c4aa6d35505a500782d1e0adaf4abd48ebb1dfd/Rakefile#L21-L22) in some extensions, maybe only auth devise but it's still a use case to consider. With the current implementation there not seem to be a way to pass parameters.
- the README should tell people to remove current content from the Rakefile along with adding the suggested lines.

**Comment by aldesantis** [comment]
@kennyadsl I don't know if we really need to preserve backwards compatibility. When people are switching to solidus_dev_support, they know they should expect some breaking changes, and this is quite a minor one in comparison with everything else we've done here.

As for the task argument, considering that solidus_auth_devise is a one-of-a-kind in the Solidus ecosystem, I'm okay with the Rake task not being ideal just for that extension. I'd rather have something that works in 99% of scenarios and is simpler to reason about than give full flexibility at the expense of complexity. solidus_auth_devise can continue to use its own Rakefile. Furthermore, solidus_auth_devise also doesn't seem to use `extension:test_app` at all, but rather `common:test_app` directly, so the task wouldn't work anyway.
